# coding: utf-8

"""
    Text2Label by tfidf APIs

    Text to label by tfidf of contents.<BR />[Endpoint] https://api.apitore.com/api/18  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.text_2_label_by_tfidf_controller_api import Text2LabelByTfidfControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestText2LabelByTfidfControllerApi(unittest.TestCase):
    """Text2LabelByTfidfControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.text_2_label_by_tfidf_controller_api.Text2LabelByTfidfControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_using_get1(self):
        """Test case for get_using_get1

        Get labels from text  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
