# coding: utf-8

"""
    Synonym APIs

    Return synonymous words. (equal to \"word2vec distance\")<BR />[Endpoint] https://api.apitore.com/api/9  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.distance_entity import DistanceEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestDistanceEntity(unittest.TestCase):
    """DistanceEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistanceEntity(self):
        """Test DistanceEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.distance_entity.DistanceEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
