# coding: utf-8

"""
    Kmeans clustering by word2vec

    Kmeans clustering by word2vec.<BR />[Endpoint] https://api.apitore.com/api/48  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.clustering_request_entity import ClusteringRequestEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestClusteringRequestEntity(unittest.TestCase):
    """ClusteringRequestEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClusteringRequestEntity(self):
        """Test ClusteringRequestEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.clustering_request_entity.ClusteringRequestEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
