# coding: utf-8

"""
    Url2Label by word vector APIs

    Url to label by word2vec of contents.<BR />[Endpoint] https://api.apitore.com/api/21  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.url_2_label_by_word_vector_controller_api import Url2LabelByWordVectorControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUrl2LabelByWordVectorControllerApi(unittest.TestCase):
    """Url2LabelByWordVectorControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.url_2_label_by_word_vector_controller_api.Url2LabelByWordVectorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_using_get4(self):
        """Test case for get_using_get4

        Get labels from URL  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
