# coding: utf-8

"""
    SentencePiece APIs (wikipedia)

    SentencePiece tokenizer (wikipedia).<BR />[Endpoint] https://api.apitore.com/api/37  # noqa: E501

    OpenAPI spec version: 0.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sentence_piece_bpe_controller_api import SentencePieceBpeControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSentencePieceBpeControllerApi(unittest.TestCase):
    """SentencePieceBpeControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sentence_piece_bpe_controller_api.SentencePieceBpeControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_using_get1(self):
        """Test case for get_using_get1

        SentencePiece (bpe)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
