# coding: utf-8

# flake8: noqa
"""
    Japanese WordNet APIs

    Return all WordNet words.<BR />[Endpoint] https://api.apitore.com/api/40  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.link_words_entity import LinkWordsEntity
from swagger_client.models.links_response_entity import LinksResponseEntity
