# coding: utf-8

"""
    Pioneer blog feeds APIs

    Various blog feeds.<BR />[Endpoint] https://api.apitore.com/api/30  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rss_blog_controller_api import RssBlogControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRssBlogControllerApi(unittest.TestCase):
    """RssBlogControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rss_blog_controller_api.RssBlogControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feed_using_get2(self):
        """Test case for feed_using_get2

        Get pioneer blog feeds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
