# coding: utf-8

"""
    Pioneer blog feeds APIs

    Various blog feeds.<BR />[Endpoint] https://api.apitore.com/api/30  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.feed_entry_entity import FeedEntryEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestFeedEntryEntity(unittest.TestCase):
    """FeedEntryEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeedEntryEntity(self):
        """Test FeedEntryEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.feed_entry_entity.FeedEntryEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
