# coding: utf-8

"""
    Design feeds APIs

    Various design feeds.<BR />[Endpoint] https://api.apitore.com/api/32  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rss_design_controller_api import RssDesignControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRssDesignControllerApi(unittest.TestCase):
    """RssDesignControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rss_design_controller_api.RssDesignControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feed_using_get4(self):
        """Test case for feed_using_get4

        Get design feeds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
