# coding: utf-8

"""
    Tweet summarization APIs

    Tweet summarization.<BR />[Endpoint] https://api.apitore.com/api/27  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.twitter_summarize_response_entity import TwitterSummarizeResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterSummarizeResponseEntity(unittest.TestCase):
    """TwitterSummarizeResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwitterSummarizeResponseEntity(self):
        """Test TwitterSummarizeResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.twitter_summarize_response_entity.TwitterSummarizeResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
