# coding: utf-8

"""
    Tweet summarization APIs

    Tweet summarization.<BR />[Endpoint] https://api.apitore.com/api/27  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tweet_summarize_entity import TweetSummarizeEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestTweetSummarizeEntity(unittest.TestCase):
    """TweetSummarizeEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTweetSummarizeEntity(self):
        """Test TweetSummarizeEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tweet_summarize_entity.TweetSummarizeEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
