# coding: utf-8

# flake8: noqa

"""
    Tweet summarization APIs

    Tweet summarization.<BR />[Endpoint] https://api.apitore.com/api/27  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.twitter_simple_summarize_controller_api import TwitterSimpleSummarizeControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.tweet_summarize_entity import TweetSummarizeEntity
from swagger_client.models.twitter_summarize_response_entity import TwitterSummarizeResponseEntity
