# coding: utf-8

"""
    Url2Label by tfidf APIs

    Url to label by tfidf of contents.<BR />[Endpoint] https://api.apitore.com/api/20  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.label_response_entity import LabelResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestLabelResponseEntity(unittest.TestCase):
    """LabelResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelResponseEntity(self):
        """Test LabelResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.label_response_entity.LabelResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
