# coding: utf-8

"""
    WordNet hypernym APIs

    Return hypernym words.<BR />[Endpoint] https://api.apitore.com/api/42  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.links_response_entity import LinksResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestLinksResponseEntity(unittest.TestCase):
    """LinksResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinksResponseEntity(self):
        """Test LinksResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.links_response_entity.LinksResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
