# coding: utf-8

# flake8: noqa

"""
    Sentence separator APIs

    Simple sentence separator.<BR />[Endpoint] https://api.apitore.com/api/17  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.sentence_separator_controller_api import SentenceSeparatorControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.sentence_response_entity import SentenceResponseEntity
