# coding: utf-8

# flake8: noqa
"""
    Design feeds APIs

    Various design feeds.<BR />[Endpoint] https://api.apitore.com/api/32  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.feed_entry_entity import FeedEntryEntity
from swagger_client.models.feed_response_entity import FeedResponseEntity
