# coding: utf-8

"""
    Kuromoji APIs

    Kuromoji: japanese morphological analyzer.<BR />[Endpoint] https://api.apitore.com/api/7  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.kuromoji_ipadic_controller_api import KuromojiIpadicControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestKuromojiIpadicControllerApi(unittest.TestCase):
    """KuromojiIpadicControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.kuromoji_ipadic_controller_api.KuromojiIpadicControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tokenize_using_get(self):
        """Test case for tokenize_using_get

        Kuromoji IPADIC  # noqa: E501
        """
        pass

    def test_tokenize_using_post(self):
        """Test case for tokenize_using_post

        Kuromoji IPADIC  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
