# coding: utf-8

"""
    Kuromoji APIs

    Kuromoji: japanese morphological analyzer.<BR />[Endpoint] https://api.apitore.com/api/7  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.kuromoji_request_entity import KuromojiRequestEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestKuromojiRequestEntity(unittest.TestCase):
    """KuromojiRequestEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKuromojiRequestEntity(self):
        """Test KuromojiRequestEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.kuromoji_request_entity.KuromojiRequestEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
