# coding: utf-8

"""
    Kuromoji APIs

    Kuromoji: japanese morphological analyzer.<BR />[Endpoint] https://api.apitore.com/api/7  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.tokens_response_entity import TokensResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestTokensResponseEntity(unittest.TestCase):
    """TokensResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokensResponseEntity(self):
        """Test TokensResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.tokens_response_entity.TokensResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
