# coding: utf-8

"""
    Sentence Similarity

    Sentence Similarity.<BR />[Endpoint] https://api.apitore.com/api/53  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.text_request_entity import TextRequestEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestTextRequestEntity(unittest.TestCase):
    """TextRequestEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextRequestEntity(self):
        """Test TextRequestEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.text_request_entity.TextRequestEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
