# coding: utf-8

# flake8: noqa

"""
    Kmeans clustering by word2vec

    Kmeans clustering by word2vec.<BR />[Endpoint] https://api.apitore.com/api/48  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.kmeans_by_word_2_vec_controller_api import KmeansByWord2VecControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.cluster_entity import ClusterEntity
from swagger_client.models.cluster_response_entity import ClusterResponseEntity
from swagger_client.models.clustering_request_entity import ClusteringRequestEntity
from swagger_client.models.factor_entity import FactorEntity
