# coding: utf-8

"""
    Twitter APIs with Word2Vec query expansion, and add sentiment by Apitore sentiment API

    Call Twitter APIs with word2vec query expansion and sentiment analysis.<BR />[Endpoint] https://api.apitore.com/api/26  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.twitter_word_2_vec_with_sentiment_controller_api import TwitterWord2VecWithSentimentControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterWord2VecWithSentimentControllerApi(unittest.TestCase):
    """TwitterWord2VecWithSentimentControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.twitter_word_2_vec_with_sentiment_controller_api.TwitterWord2VecWithSentimentControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_using_get3(self):
        """Test case for search_using_get3

        Search tweets.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
