# coding: utf-8

"""
    WordNet hyponym APIs

    Return hyponym words.<BR />[Endpoint] https://api.apitore.com/api/43  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.link_words_entity import LinkWordsEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestLinkWordsEntity(unittest.TestCase):
    """LinkWordsEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkWordsEntity(self):
        """Test LinkWordsEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.link_words_entity.LinkWordsEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
