# coding: utf-8

# flake8: noqa

"""
    Design feeds APIs

    Various design feeds.<BR />[Endpoint] https://api.apitore.com/api/32  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.rss_design_controller_api import RssDesignControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.feed_entry_entity import FeedEntryEntity
from swagger_client.models.feed_response_entity import FeedResponseEntity
