# coding: utf-8

"""
    Sentiment APIs

    Japanese sentiment analyzer.<BR />[Endpoint] https://api.apitore.com/api/52  # noqa: E501

    OpenAPI spec version: 1.0.6
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.list_sentiment_response_entity import ListSentimentResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestListSentimentResponseEntity(unittest.TestCase):
    """ListSentimentResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListSentimentResponseEntity(self):
        """Test ListSentimentResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.list_sentiment_response_entity.ListSentimentResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
