# coding: utf-8

"""
    Twitter APIs with Word2Vec query expansion

    Call Twitter APIs with word2vec query expansion.<BR />[Endpoint] https://api.apitore.com/api/24  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.twitter_word_2_vec_controller_api import TwitterWord2VecControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterWord2VecControllerApi(unittest.TestCase):
    """TwitterWord2VecControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.twitter_word_2_vec_controller_api.TwitterWord2VecControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_using_get2(self):
        """Test case for search_using_get2

        Search tweets.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
