# coding: utf-8

# flake8: noqa

"""
    WordNet Similarity APIs

    Calculate word similarity.<BR />[Endpoint] https://api.apitore.com/api/47  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.wordnet_similarity_controller_api import WordnetSimilarityControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.wordnet_similarity_response_entity import WordnetSimilarityResponseEntity
