# coding: utf-8

"""
    Document frequency APIs

    Document frequency of Wikipedia.<BR />[Endpoint] https://api.apitore.com/api/16  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.document_frequency_controller_api import DocumentFrequencyControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentFrequencyControllerApi(unittest.TestCase):
    """DocumentFrequencyControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.document_frequency_controller_api.DocumentFrequencyControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_using_get(self):
        """Test case for get_using_get

        Get document frequency  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
