# coding: utf-8

"""
    Document frequency APIs

    Document frequency of Wikipedia.<BR />[Endpoint] https://api.apitore.com/api/16  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.document_frequency_response_entity import DocumentFrequencyResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentFrequencyResponseEntity(unittest.TestCase):
    """DocumentFrequencyResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocumentFrequencyResponseEntity(self):
        """Test DocumentFrequencyResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.document_frequency_response_entity.DocumentFrequencyResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
