# coding: utf-8

# flake8: noqa

"""
    Url2Label by tfidf APIs

    Url to label by tfidf of contents.<BR />[Endpoint] https://api.apitore.com/api/20  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.url_2_label_by_tfidf_controller_api import Url2LabelByTfidfControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.label_entity import LabelEntity
from swagger_client.models.label_response_entity import LabelResponseEntity
