# coding: utf-8

# flake8: noqa
"""
    Document frequency APIs

    Document frequency of Wikipedia.<BR />[Endpoint] https://api.apitore.com/api/16  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.document_frequency_response_entity import DocumentFrequencyResponseEntity
