# coding: utf-8

"""
    Document frequency APIs

    Document frequency of Wikipedia.<BR />[Endpoint] https://api.apitore.com/api/16  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DocumentFrequencyResponseEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'document_frequency': 'float',
        'end_time': 'str',
        'log': 'str',
        'process_time': 'str',
        'start_time': 'str',
        'word': 'str'
    }

    attribute_map = {
        'document_frequency': 'documentFrequency',
        'end_time': 'endTime',
        'log': 'log',
        'process_time': 'processTime',
        'start_time': 'startTime',
        'word': 'word'
    }

    def __init__(self, document_frequency=None, end_time=None, log=None, process_time=None, start_time=None, word=None):  # noqa: E501
        """DocumentFrequencyResponseEntity - a model defined in Swagger"""  # noqa: E501

        self._document_frequency = None
        self._end_time = None
        self._log = None
        self._process_time = None
        self._start_time = None
        self._word = None
        self.discriminator = None

        self.document_frequency = document_frequency
        self.end_time = end_time
        self.log = log
        self.process_time = process_time
        self.start_time = start_time
        self.word = word

    @property
    def document_frequency(self):
        """Gets the document_frequency of this DocumentFrequencyResponseEntity.  # noqa: E501

        Output: document frequency  # noqa: E501

        :return: The document_frequency of this DocumentFrequencyResponseEntity.  # noqa: E501
        :rtype: float
        """
        return self._document_frequency

    @document_frequency.setter
    def document_frequency(self, document_frequency):
        """Sets the document_frequency of this DocumentFrequencyResponseEntity.

        Output: document frequency  # noqa: E501

        :param document_frequency: The document_frequency of this DocumentFrequencyResponseEntity.  # noqa: E501
        :type: float
        """
        if document_frequency is None:
            raise ValueError("Invalid value for `document_frequency`, must not be `None`")  # noqa: E501

        self._document_frequency = document_frequency

    @property
    def end_time(self):
        """Gets the end_time of this DocumentFrequencyResponseEntity.  # noqa: E501

        End date  # noqa: E501

        :return: The end_time of this DocumentFrequencyResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this DocumentFrequencyResponseEntity.

        End date  # noqa: E501

        :param end_time: The end_time of this DocumentFrequencyResponseEntity.  # noqa: E501
        :type: str
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def log(self):
        """Gets the log of this DocumentFrequencyResponseEntity.  # noqa: E501

        Log message  # noqa: E501

        :return: The log of this DocumentFrequencyResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._log

    @log.setter
    def log(self, log):
        """Sets the log of this DocumentFrequencyResponseEntity.

        Log message  # noqa: E501

        :param log: The log of this DocumentFrequencyResponseEntity.  # noqa: E501
        :type: str
        """
        if log is None:
            raise ValueError("Invalid value for `log`, must not be `None`")  # noqa: E501

        self._log = log

    @property
    def process_time(self):
        """Gets the process_time of this DocumentFrequencyResponseEntity.  # noqa: E501

        Process time [millisecond]  # noqa: E501

        :return: The process_time of this DocumentFrequencyResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._process_time

    @process_time.setter
    def process_time(self, process_time):
        """Sets the process_time of this DocumentFrequencyResponseEntity.

        Process time [millisecond]  # noqa: E501

        :param process_time: The process_time of this DocumentFrequencyResponseEntity.  # noqa: E501
        :type: str
        """
        if process_time is None:
            raise ValueError("Invalid value for `process_time`, must not be `None`")  # noqa: E501

        self._process_time = process_time

    @property
    def start_time(self):
        """Gets the start_time of this DocumentFrequencyResponseEntity.  # noqa: E501

        Start date  # noqa: E501

        :return: The start_time of this DocumentFrequencyResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this DocumentFrequencyResponseEntity.

        Start date  # noqa: E501

        :param start_time: The start_time of this DocumentFrequencyResponseEntity.  # noqa: E501
        :type: str
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def word(self):
        """Gets the word of this DocumentFrequencyResponseEntity.  # noqa: E501

        Input: word  # noqa: E501

        :return: The word of this DocumentFrequencyResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._word

    @word.setter
    def word(self, word):
        """Sets the word of this DocumentFrequencyResponseEntity.

        Input: word  # noqa: E501

        :param word: The word of this DocumentFrequencyResponseEntity.  # noqa: E501
        :type: str
        """
        if word is None:
            raise ValueError("Invalid value for `word`, must not be `None`")  # noqa: E501

        self._word = word

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DocumentFrequencyResponseEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
