# coding: utf-8

# flake8: noqa
"""
    Tech feeds APIs

    Various tech feeds.<BR />[Endpoint] https://api.apitore.com/api/35  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.feed_entry_entity import FeedEntryEntity
from swagger_client.models.feed_response_entity import FeedResponseEntity
