# coding: utf-8

"""
    Tweet summarization APIs

    Tweet summarization.<BR />[Endpoint] https://api.apitore.com/api/27  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.tweet_summarize_entity import TweetSummarizeEntity  # noqa: F401,E501


class TwitterSummarizeResponseEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_time': 'str',
        'log': 'str',
        'numof_summarize': 'int',
        'numof_tweets': 'int',
        'process_time': 'str',
        'query': 'str',
        'start_time': 'str',
        'tweets': 'list[TweetSummarizeEntity]'
    }

    attribute_map = {
        'end_time': 'endTime',
        'log': 'log',
        'numof_summarize': 'numofSummarize',
        'numof_tweets': 'numofTweets',
        'process_time': 'processTime',
        'query': 'query',
        'start_time': 'startTime',
        'tweets': 'tweets'
    }

    def __init__(self, end_time=None, log=None, numof_summarize=None, numof_tweets=None, process_time=None, query=None, start_time=None, tweets=None):  # noqa: E501
        """TwitterSummarizeResponseEntity - a model defined in Swagger"""  # noqa: E501

        self._end_time = None
        self._log = None
        self._numof_summarize = None
        self._numof_tweets = None
        self._process_time = None
        self._query = None
        self._start_time = None
        self._tweets = None
        self.discriminator = None

        self.end_time = end_time
        self.log = log
        self.numof_summarize = numof_summarize
        self.numof_tweets = numof_tweets
        self.process_time = process_time
        self.query = query
        self.start_time = start_time
        self.tweets = tweets

    @property
    def end_time(self):
        """Gets the end_time of this TwitterSummarizeResponseEntity.  # noqa: E501

        End date  # noqa: E501

        :return: The end_time of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this TwitterSummarizeResponseEntity.

        End date  # noqa: E501

        :param end_time: The end_time of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: str
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def log(self):
        """Gets the log of this TwitterSummarizeResponseEntity.  # noqa: E501

        Log message  # noqa: E501

        :return: The log of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._log

    @log.setter
    def log(self, log):
        """Sets the log of this TwitterSummarizeResponseEntity.

        Log message  # noqa: E501

        :param log: The log of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: str
        """
        if log is None:
            raise ValueError("Invalid value for `log`, must not be `None`")  # noqa: E501

        self._log = log

    @property
    def numof_summarize(self):
        """Gets the numof_summarize of this TwitterSummarizeResponseEntity.  # noqa: E501

        Output: Numof summarize  # noqa: E501

        :return: The numof_summarize of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: int
        """
        return self._numof_summarize

    @numof_summarize.setter
    def numof_summarize(self, numof_summarize):
        """Sets the numof_summarize of this TwitterSummarizeResponseEntity.

        Output: Numof summarize  # noqa: E501

        :param numof_summarize: The numof_summarize of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: int
        """
        if numof_summarize is None:
            raise ValueError("Invalid value for `numof_summarize`, must not be `None`")  # noqa: E501

        self._numof_summarize = numof_summarize

    @property
    def numof_tweets(self):
        """Gets the numof_tweets of this TwitterSummarizeResponseEntity.  # noqa: E501

        Output: Numof hit tweets  # noqa: E501

        :return: The numof_tweets of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: int
        """
        return self._numof_tweets

    @numof_tweets.setter
    def numof_tweets(self, numof_tweets):
        """Sets the numof_tweets of this TwitterSummarizeResponseEntity.

        Output: Numof hit tweets  # noqa: E501

        :param numof_tweets: The numof_tweets of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: int
        """
        if numof_tweets is None:
            raise ValueError("Invalid value for `numof_tweets`, must not be `None`")  # noqa: E501

        self._numof_tweets = numof_tweets

    @property
    def process_time(self):
        """Gets the process_time of this TwitterSummarizeResponseEntity.  # noqa: E501

        Process time [millisecond]  # noqa: E501

        :return: The process_time of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._process_time

    @process_time.setter
    def process_time(self, process_time):
        """Sets the process_time of this TwitterSummarizeResponseEntity.

        Process time [millisecond]  # noqa: E501

        :param process_time: The process_time of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: str
        """
        if process_time is None:
            raise ValueError("Invalid value for `process_time`, must not be `None`")  # noqa: E501

        self._process_time = process_time

    @property
    def query(self):
        """Gets the query of this TwitterSummarizeResponseEntity.  # noqa: E501

        Input: query  # noqa: E501

        :return: The query of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this TwitterSummarizeResponseEntity.

        Input: query  # noqa: E501

        :param query: The query of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    @property
    def start_time(self):
        """Gets the start_time of this TwitterSummarizeResponseEntity.  # noqa: E501

        Start date  # noqa: E501

        :return: The start_time of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this TwitterSummarizeResponseEntity.

        Start date  # noqa: E501

        :param start_time: The start_time of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: str
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def tweets(self):
        """Gets the tweets of this TwitterSummarizeResponseEntity.  # noqa: E501

        Output: Summarization tweets  # noqa: E501

        :return: The tweets of this TwitterSummarizeResponseEntity.  # noqa: E501
        :rtype: list[TweetSummarizeEntity]
        """
        return self._tweets

    @tweets.setter
    def tweets(self, tweets):
        """Sets the tweets of this TwitterSummarizeResponseEntity.

        Output: Summarization tweets  # noqa: E501

        :param tweets: The tweets of this TwitterSummarizeResponseEntity.  # noqa: E501
        :type: list[TweetSummarizeEntity]
        """
        if tweets is None:
            raise ValueError("Invalid value for `tweets`, must not be `None`")  # noqa: E501

        self._tweets = tweets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TwitterSummarizeResponseEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
