# coding: utf-8

"""
    Tech feeds APIs

    Various tech feeds.<BR />[Endpoint] https://api.apitore.com/api/35  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rss_tech_controller_api import RssTechControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRssTechControllerApi(unittest.TestCase):
    """RssTechControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rss_tech_controller_api.RssTechControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feed_using_get7(self):
        """Test case for feed_using_get7

        Get tech feeds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
