# coding: utf-8

"""
    Text2Label by word vector APIs

    Text to label by word2vec of contents.<BR />[Endpoint] https://api.apitore.com/api/19  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.text_2_label_by_word_vector_controller_api import Text2LabelByWordVectorControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestText2LabelByWordVectorControllerApi(unittest.TestCase):
    """Text2LabelByWordVectorControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.text_2_label_by_word_vector_controller_api.Text2LabelByWordVectorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_using_get2(self):
        """Test case for get_using_get2

        Get labels from text  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
