# coding: utf-8

# flake8: noqa

"""
    SentencePiece APIs (tweet)

    SentencePiece tokenizer (tweet).<BR />[Endpoint] https://api.apitore.com/api/38  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.sentence_piece_bpe_tweet_controller_api import SentencePieceBpeTweetControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.sp_token_entity import SPTokenEntity
from swagger_client.models.sentence_piece_token_response_entity import SentencePieceTokenResponseEntity
