# coding: utf-8

# flake8: noqa
"""
    Url2Label by word vector APIs

    Url to label by word2vec of contents.<BR />[Endpoint] https://api.apitore.com/api/21  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.label_entity import LabelEntity
from swagger_client.models.label_response_entity import LabelResponseEntity
