# coding: utf-8

# flake8: noqa

"""
    Cosine Similarity

    Cosine Similarity.<BR />[Endpoint] https://api.apitore.com/api/49  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.cosine_similarity_controller_api import CosineSimilarityControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.similarity_response_entity import SimilarityResponseEntity
from swagger_client.models.vecvec_request_entity import VecvecRequestEntity
from swagger_client.models.vecword_request_entity import VecwordRequestEntity
