# coding: utf-8

"""
    Sentiment APIs

    Japanese sentiment analyzer. (tokenized by SentencePiece)<BR />[Endpoint] https://api.apitore.com/api/39  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sentiment_v_2_controller_api import SentimentV2ControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSentimentV2ControllerApi(unittest.TestCase):
    """SentimentV2ControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sentiment_v_2_controller_api.SentimentV2ControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_predict_using_get(self):
        """Test case for predict_using_get

        Sentiment predict  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
