# coding: utf-8

# flake8: noqa

"""
    WordNet hyponym APIs

    Return hyponym words.<BR />[Endpoint] https://api.apitore.com/api/43  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.wordnet_simple_parts_controller_api import WordnetSimplePartsControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.link_words_entity import LinkWordsEntity
from swagger_client.models.links_response_entity import LinksResponseEntity
