# coding: utf-8

"""
    Words to Vectors APIs

    Word to vectors.<BR />[Endpoint] https://api.apitore.com/api/10  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.word_vector_response_entity import WordVectorResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestWordVectorResponseEntity(unittest.TestCase):
    """WordVectorResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWordVectorResponseEntity(self):
        """Test WordVectorResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.word_vector_response_entity.WordVectorResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
