# coding: utf-8

"""
    2ch matome feeds APIs

    Various 2ch matome feeds.<BR />[Endpoint] https://api.apitore.com/api/29  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rss_2ch_controller_api import Rss2chControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRss2chControllerApi(unittest.TestCase):
    """Rss2chControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rss_2ch_controller_api.Rss2chControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feed_using_get(self):
        """Test case for feed_using_get

        Get 2ch matome feeds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
