# coding: utf-8

"""
    Kmeans clustering by word2vec

    Kmeans clustering by word2vec.<BR />[Endpoint] https://api.apitore.com/api/48  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FactorEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'similarity': 'float',
        'word': 'str'
    }

    attribute_map = {
        'similarity': 'similarity',
        'word': 'word'
    }

    def __init__(self, similarity=None, word=None):  # noqa: E501
        """FactorEntity - a model defined in Swagger"""  # noqa: E501

        self._similarity = None
        self._word = None
        self.discriminator = None

        self.similarity = similarity
        self.word = word

    @property
    def similarity(self):
        """Gets the similarity of this FactorEntity.  # noqa: E501

        similarity  # noqa: E501

        :return: The similarity of this FactorEntity.  # noqa: E501
        :rtype: float
        """
        return self._similarity

    @similarity.setter
    def similarity(self, similarity):
        """Sets the similarity of this FactorEntity.

        similarity  # noqa: E501

        :param similarity: The similarity of this FactorEntity.  # noqa: E501
        :type: float
        """
        if similarity is None:
            raise ValueError("Invalid value for `similarity`, must not be `None`")  # noqa: E501

        self._similarity = similarity

    @property
    def word(self):
        """Gets the word of this FactorEntity.  # noqa: E501

        word  # noqa: E501

        :return: The word of this FactorEntity.  # noqa: E501
        :rtype: str
        """
        return self._word

    @word.setter
    def word(self, word):
        """Sets the word of this FactorEntity.

        word  # noqa: E501

        :param word: The word of this FactorEntity.  # noqa: E501
        :type: str
        """
        if word is None:
            raise ValueError("Invalid value for `word`, must not be `None`")  # noqa: E501

        self._word = word

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FactorEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
