# coding: utf-8

"""
    Url2Href APIs

    Url to Href links.<BR />[Endpoint] https://api.apitore.com/api/14  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.link_response_entity import LinkResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestLinkResponseEntity(unittest.TestCase):
    """LinkResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLinkResponseEntity(self):
        """Test LinkResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.link_response_entity.LinkResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
