# coding: utf-8

"""
    Cosine Similarity

    Cosine Similarity.<BR />[Endpoint] https://api.apitore.com/api/49  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cosine_similarity_controller_api import CosineSimilarityControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCosineSimilarityControllerApi(unittest.TestCase):
    """CosineSimilarityControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cosine_similarity_controller_api.CosineSimilarityControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_vec_vec_using_post(self):
        """Test case for vec_vec_using_post

        Calclate similarity  # noqa: E501
        """
        pass

    def test_vec_word_using_post(self):
        """Test case for vec_word_using_post

        Calclate similarity by word  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
