# coding: utf-8

"""
    Cosine Similarity

    Cosine Similarity.<BR />[Endpoint] https://api.apitore.com/api/49  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.vecword_request_entity import VecwordRequestEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestVecwordRequestEntity(unittest.TestCase):
    """VecwordRequestEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVecwordRequestEntity(self):
        """Test VecwordRequestEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.vecword_request_entity.VecwordRequestEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
