# coding: utf-8

"""
    WordNet Similarity APIs

    Calculate word similarity.<BR />[Endpoint] https://api.apitore.com/api/47  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.wordnet_similarity_response_entity import WordnetSimilarityResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestWordnetSimilarityResponseEntity(unittest.TestCase):
    """WordnetSimilarityResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWordnetSimilarityResponseEntity(self):
        """Test WordnetSimilarityResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.wordnet_similarity_response_entity.WordnetSimilarityResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
