# coding: utf-8

"""
    WordNet Similarity APIs

    Calculate word similarity.<BR />[Endpoint] https://api.apitore.com/api/47  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wordnet_similarity_controller_api import WordnetSimilarityControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWordnetSimilarityControllerApi(unittest.TestCase):
    """WordnetSimilarityControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wordnet_similarity_controller_api.WordnetSimilarityControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_hirststonge_using_get(self):
        """Test case for hirststonge_using_get

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get1(self):
        """Test case for hirststonge_using_get1

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get2(self):
        """Test case for hirststonge_using_get2

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get3(self):
        """Test case for hirststonge_using_get3

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get4(self):
        """Test case for hirststonge_using_get4

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get5(self):
        """Test case for hirststonge_using_get5

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get6(self):
        """Test case for hirststonge_using_get6

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass

    def test_hirststonge_using_get7(self):
        """Test case for hirststonge_using_get7

        WordNet Similarity WebAPI.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
