# coding: utf-8

"""
    Sentence separator APIs

    Simple sentence separator.<BR />[Endpoint] https://api.apitore.com/api/17  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.sentence_response_entity import SentenceResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestSentenceResponseEntity(unittest.TestCase):
    """SentenceResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSentenceResponseEntity(self):
        """Test SentenceResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.sentence_response_entity.SentenceResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
