# coding: utf-8

"""
    Sentence separator APIs

    Simple sentence separator.<BR />[Endpoint] https://api.apitore.com/api/17  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sentence_separator_controller_api import SentenceSeparatorControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSentenceSeparatorControllerApi(unittest.TestCase):
    """SentenceSeparatorControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sentence_separator_controller_api.SentenceSeparatorControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_heuristics_using_get(self):
        """Test case for heuristics_using_get

        Separate from text to sentence.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
