# coding: utf-8

# flake8: noqa

"""
    Words to Vectors APIs

    Word to vectors.<BR />[Endpoint] https://api.apitore.com/api/10  # noqa: E501

    OpenAPI spec version: 1.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.word_2_vec_controller_api import Word2VecControllerApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.word_vector_response_entity import WordVectorResponseEntity
