# coding: utf-8

"""
    Language Detection APIs

    Language detection.<BR />[Endpoint] https://api.apitore.com/api/22  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.language_entity import LanguageEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestLanguageEntity(unittest.TestCase):
    """LanguageEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguageEntity(self):
        """Test LanguageEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.language_entity.LanguageEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
