# coding: utf-8

"""
    WordNet APIs

    You can access ALL WordNet DB.<BR />[Endpoint] https://api.apitore.com/api/46  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.synset_entity import SynsetEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestSynsetEntity(unittest.TestCase):
    """SynsetEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSynsetEntity(self):
        """Test SynsetEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.synset_entity.SynsetEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
