# coding: utf-8

"""
    Cosine Similarity

    Cosine Similarity.<BR />[Endpoint] https://api.apitore.com/api/49  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VecwordRequestEntity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'vec': 'list[float]',
        'word': 'str'
    }

    attribute_map = {
        'vec': 'vec',
        'word': 'word'
    }

    def __init__(self, vec=None, word=None):  # noqa: E501
        """VecwordRequestEntity - a model defined in Swagger"""  # noqa: E501

        self._vec = None
        self._word = None
        self.discriminator = None

        self.vec = vec
        self.word = word

    @property
    def vec(self):
        """Gets the vec of this VecwordRequestEntity.  # noqa: E501

        Vector  # noqa: E501

        :return: The vec of this VecwordRequestEntity.  # noqa: E501
        :rtype: list[float]
        """
        return self._vec

    @vec.setter
    def vec(self, vec):
        """Sets the vec of this VecwordRequestEntity.

        Vector  # noqa: E501

        :param vec: The vec of this VecwordRequestEntity.  # noqa: E501
        :type: list[float]
        """
        if vec is None:
            raise ValueError("Invalid value for `vec`, must not be `None`")  # noqa: E501

        self._vec = vec

    @property
    def word(self):
        """Gets the word of this VecwordRequestEntity.  # noqa: E501

        Word  # noqa: E501

        :return: The word of this VecwordRequestEntity.  # noqa: E501
        :rtype: str
        """
        return self._word

    @word.setter
    def word(self, word):
        """Sets the word of this VecwordRequestEntity.

        Word  # noqa: E501

        :param word: The word of this VecwordRequestEntity.  # noqa: E501
        :type: str
        """
        if word is None:
            raise ValueError("Invalid value for `word`, must not be `None`")  # noqa: E501

        self._word = word

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VecwordRequestEntity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
