# coding: utf-8

"""
    Twitter APIs with sentiment by Apitore sentiment API

    Call Twitter APIs with sentiment by Apitore sentiment API.<BR />[Endpoint] https://api.apitore.com/api/25  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.twitter_simple_with_sentiment_controller_api import TwitterSimpleWithSentimentControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterSimpleWithSentimentControllerApi(unittest.TestCase):
    """TwitterSimpleWithSentimentControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.twitter_simple_with_sentiment_controller_api.TwitterSimpleWithSentimentControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_search_using_get1(self):
        """Test case for search_using_get1

        Search tweets.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
