# coding: utf-8

"""
    Url2Html APIs

    Url to Html.<BR />[Endpoint] https://api.apitore.com/api/12  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.text_response_entity import TextResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestTextResponseEntity(unittest.TestCase):
    """TextResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTextResponseEntity(self):
        """Test TextResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.text_response_entity.TextResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
