# coding: utf-8

# flake8: noqa
"""
    SentencePiece APIs (wikipedia)

    SentencePiece tokenizer (wikipedia).<BR />[Endpoint] https://api.apitore.com/api/37  # noqa: E501

    OpenAPI spec version: 0.0.3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.sp_token_entity import SPTokenEntity
from swagger_client.models.sentence_piece_token_response_entity import SentencePieceTokenResponseEntity
