# coding: utf-8

"""
    News feeds APIs

    Various news feeds.<BR />[Endpoint] https://api.apitore.com/api/34  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rss_news_controller_api import RssNewsControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRssNewsControllerApi(unittest.TestCase):
    """RssNewsControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rss_news_controller_api.RssNewsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feed_using_get6(self):
        """Test case for feed_using_get6

        Get news feeds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
