# coding: utf-8

"""
    Certificate feeds APIs

    Various certificate feeds.<BR />[Endpoint] https://api.apitore.com/api/31  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rss_certificate_controller_api import RssCertificateControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRssCertificateControllerApi(unittest.TestCase):
    """RssCertificateControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rss_certificate_controller_api.RssCertificateControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_feed_using_get3(self):
        """Test case for feed_using_get3

        Get certificate feeds  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
