# coding: utf-8

"""
    Japanese WordNet APIs

    Return all WordNet words.<BR />[Endpoint] https://api.apitore.com/api/40  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wordnet_simple_controller_api import WordnetSimpleControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWordnetSimpleControllerApi(unittest.TestCase):
    """WordnetSimpleControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.wordnet_simple_controller_api.WordnetSimpleControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_simple_all_using_get(self):
        """Test case for simple_all_using_get

        Simple WordNet WebAPI. Return words such as synonyms, hypernyms, etc...  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
