# coding: utf-8

# flake8: noqa
"""
    Twitter APIs with sentiment by Apitore sentiment API

    Call Twitter APIs with sentiment by Apitore sentiment API.<BR />[Endpoint] https://api.apitore.com/api/25  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.tweet_entity import TweetEntity
from swagger_client.models.twitter_response_entity import TwitterResponseEntity
