# coding: utf-8

"""
    Twitter APIs

    Call Twitter APIs.<BR />[Endpoint] https://api.apitore.com/api/23  # noqa: E501

    OpenAPI spec version: 0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.twitter_response_entity import TwitterResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterResponseEntity(unittest.TestCase):
    """TwitterResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTwitterResponseEntity(self):
        """Test TwitterResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.twitter_response_entity.TwitterResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
