# coding: utf-8

"""
    Twitter APIs

    Call Twitter APIs.<BR />[Endpoint] https://api.apitore.com/api/23  # noqa: E501

    OpenAPI spec version: 0.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.twitter_simple_controller_api import TwitterSimpleControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTwitterSimpleControllerApi(unittest.TestCase):
    """TwitterSimpleControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.twitter_simple_controller_api.TwitterSimpleControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_my_timeline_using_get(self):
        """Test case for my_timeline_using_get

        Get my tweets.  # noqa: E501
        """
        pass

    def test_my_tweet_using_get(self):
        """Test case for my_tweet_using_get

        Get my tweets.  # noqa: E501
        """
        pass

    def test_search_using_get(self):
        """Test case for search_using_get

        Search tweets.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
