# coding: utf-8

"""
    RSS2JSON APIs

    Rss to Json.<BR />[Endpoint] https://api.apitore.com/api/28  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rome_controller_api import RomeControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRomeControllerApi(unittest.TestCase):
    """RomeControllerApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rome_controller_api.RomeControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_rss2json_using_get(self):
        """Test case for rss2json_using_get

        RSS to JSON  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
