# coding: utf-8

"""
    Word2Vec APIs

    Word2Vec.<BR />[Endpoint] https://api.apitore.com/api/8  # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.distance_response_entity import DistanceResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestDistanceResponseEntity(unittest.TestCase):
    """DistanceResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistanceResponseEntity(self):
        """Test DistanceResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.distance_response_entity.DistanceResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
