# coding: utf-8

"""
    Word2Vec APIs

    Word2Vec.<BR />[Endpoint] https://api.apitore.com/api/8  # noqa: E501

    OpenAPI spec version: 1.0.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.analogy_response_entity import AnalogyResponseEntity  # noqa: E501
from swagger_client.rest import ApiException


class TestAnalogyResponseEntity(unittest.TestCase):
    """AnalogyResponseEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalogyResponseEntity(self):
        """Test AnalogyResponseEntity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.analogy_response_entity.AnalogyResponseEntity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
